#!/usr/bin/env node

require('dotenv').config()
const os = require('os');
const { spawn } = require('child_process');
const fetch = require('node-fetch');
const express = require('express');
const app = express();

app.listen(2112, () => {
});

function getStatus() {
  const averages = os.loadavg();
  const cpus = os.cpus();
  const totalmem = os.totalmem();
  const freemem = os.freemem();
  const freemempercent = freemem / totalmem * 100.0;
  const loadpercent = (averages[0] / cpus.length) * 100.0;
  const interfaces = os.networkInterfaces();
  const interface = Object.values(interfaces).flat().find(interface => !interface.internal && interface.family === 'IPv4')

  return {
    hostname: os.hostname(),
    load: averages[0],
    loadpercent: loadpercent,
    cpus: cpus.length,
    uptime: os.uptime(),
    totalmem: totalmem,
    freemem: freemem,
    freemempercent: freemempercent,
    interfaces: interfaces,
    interface: interface
  };
}

app.get("/status", (req, res, next) => {
  res.json(getStatus());
});

app.post("/poweroff", (req, res, next) => {
  const process = spawn('sudo', ['poweroff']);
  process.stderr.on('data', data => {
    res.json({error: data});
  });
});

setInterval(() => {
  fetch(`${process.env.CENTRAL_URL}/ping`, {method: 'POST', body: JSON.stringify(getStatus()), headers: {'Content-Type': 'application/json'}})
    .then(it => it.json())
    .then(data => {
      // anything to do with the response?
    })
    .catch(error => {});
}, 10000);
