#!/usr/bin/env node

const os = require('os');
const express = require('express');
const app = express();

app.listen(2112, () => {
});

const averages = os.loadavg();
const cpus = os.cpus();
const totalmem = os.totalmem();
const freemem = os.freemem();
const freemempercent = freemem / totalmem * 100.0;

app.get("/status", (req, res, next) => {
  res.json({
    load: averages[2],
    cpus: cpus.length,
    uptime: os.uptime(),
    totalmem: totalmem,
    freemem: freemem,
    freemempercent: freemempercent
  });
});

